runtime: python311
entrypoint: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0

env_variables:
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10 